
package com.pachira.tts.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VoiceInterface", targetNamespace = "http://service.ws.voice.pachira.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VoiceInterface {


    /**
     * 语音合成
     * 
     * @param param
     * @return
     *     returns com.pachira.tts.ws.client.TtsResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "synthesizeText", targetNamespace = "http://service.ws.voice.pachira.com/", className = "com.pachira.tts.ws.client.SynthesizeText")
    @ResponseWrapper(localName = "synthesizeTextResponse", targetNamespace = "http://service.ws.voice.pachira.com/", className = "com.pachira.tts.ws.client.SynthesizeTextResponse")
    public TtsResponse synthesizeText(
        @WebParam(name = "param", targetNamespace = "")
        TtsParam param);

}
