
package com.pachira.tts.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VoiceInterfaceService", targetNamespace = "http://service.ws.voice.pachira.com/", wsdlLocation = "http://172.22.144.127:8080/voice/ws/wstts?wsdl")
public class VoiceInterfaceService
    extends Service
{

    private final static URL VOICEINTERFACESERVICE_WSDL_LOCATION;
    private final static WebServiceException VOICEINTERFACESERVICE_EXCEPTION;
    private final static QName VOICEINTERFACESERVICE_QNAME = new QName("http://service.ws.voice.pachira.com/", "VoiceInterfaceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.22.144.127:8080/voice/ws/wstts?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VOICEINTERFACESERVICE_WSDL_LOCATION = url;
        VOICEINTERFACESERVICE_EXCEPTION = e;
    }

    public VoiceInterfaceService() {
        super(__getWsdlLocation(), VOICEINTERFACESERVICE_QNAME);
    }

    public VoiceInterfaceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VOICEINTERFACESERVICE_QNAME, features);
    }

    public VoiceInterfaceService(URL wsdlLocation) {
        super(wsdlLocation, VOICEINTERFACESERVICE_QNAME);
    }

    public VoiceInterfaceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VOICEINTERFACESERVICE_QNAME, features);
    }

    public VoiceInterfaceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VoiceInterfaceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VoiceInterface
     */
    @WebEndpoint(name = "VoiceInterfacePort")
    public VoiceInterface getVoiceInterfacePort() {
        return super.getPort(new QName("http://service.ws.voice.pachira.com/", "VoiceInterfacePort"), VoiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VoiceInterface
     */
    @WebEndpoint(name = "VoiceInterfacePort")
    public VoiceInterface getVoiceInterfacePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ws.voice.pachira.com/", "VoiceInterfacePort"), VoiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VOICEINTERFACESERVICE_EXCEPTION!= null) {
            throw VOICEINTERFACESERVICE_EXCEPTION;
        }
        return VOICEINTERFACESERVICE_WSDL_LOCATION;
    }

}
