
package com.pachira.tts.ws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * 普强TTS WebService对外开放接口
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VoiceInterface", targetNamespace = "http://service.ws.voice.pachira.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VoiceInterface {


    /**
     * 通过byte[]上传人声音频
     * 
     * @param isOverwrite
     * @param datas
     * @param wavName
     * @param language
     * @return
     *     returns com.pachira.tts.ws.client.MyResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadWav", targetNamespace = "http://service.ws.voice.pachira.com/", className = "com.pachira.tts.ws.client.UploadWav")
    @ResponseWrapper(localName = "uploadWavResponse", targetNamespace = "http://service.ws.voice.pachira.com/", className = "com.pachira.tts.ws.client.UploadWavResponse")
    public MyResp uploadWav(
        @WebParam(name = "datas", targetNamespace = "")
        List<byte[]> datas,
        @WebParam(name = "wavName", targetNamespace = "")
        String wavName,
        @WebParam(name = "language", targetNamespace = "")
        String language,
        @WebParam(name = "isOverwrite", targetNamespace = "")
        boolean isOverwrite);

    /**
     * 获取当前系统版本号
     * 
     * @return
     *     returns com.pachira.tts.ws.client.MyResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://service.ws.voice.pachira.com/", className = "com.pachira.tts.ws.client.GetVersion")
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://service.ws.voice.pachira.com/", className = "com.pachira.tts.ws.client.GetVersionResponse")
    public MyResp getVersion();

    /**
     * 语音合成
     * 
     * @param param
     * @return
     *     returns com.pachira.tts.ws.client.TtsResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "synthesizeText", targetNamespace = "http://service.ws.voice.pachira.com/", className = "com.pachira.tts.ws.client.SynthesizeText")
    @ResponseWrapper(localName = "synthesizeTextResponse", targetNamespace = "http://service.ws.voice.pachira.com/", className = "com.pachira.tts.ws.client.SynthesizeTextResponse")
    public TtsResponse synthesizeText(
        @WebParam(name = "param", targetNamespace = "")
        TtsParam param);

    /**
     * 获取已上传人声音频名称列表
     * 
     * @param language
     * @return
     *     returns com.pachira.tts.ws.client.MyResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWavNames", targetNamespace = "http://service.ws.voice.pachira.com/", className = "com.pachira.tts.ws.client.GetWavNames")
    @ResponseWrapper(localName = "getWavNamesResponse", targetNamespace = "http://service.ws.voice.pachira.com/", className = "com.pachira.tts.ws.client.GetWavNamesResponse")
    public MyResp getWavNames(
        @WebParam(name = "language", targetNamespace = "")
        String language);

    /**
     * 通过MyByte对象上传人声音频
     * 
     * @param mybytes
     * @param isOverwrite
     * @param wavName
     * @param language
     * @return
     *     returns com.pachira.tts.ws.client.MyResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadWavByMybyte", targetNamespace = "http://service.ws.voice.pachira.com/", className = "com.pachira.tts.ws.client.UploadWavByMybyte")
    @ResponseWrapper(localName = "uploadWavByMybyteResponse", targetNamespace = "http://service.ws.voice.pachira.com/", className = "com.pachira.tts.ws.client.UploadWavByMybyteResponse")
    public MyResp uploadWavByMybyte(
        @WebParam(name = "mybytes", targetNamespace = "")
        List<MyByte> mybytes,
        @WebParam(name = "wavName", targetNamespace = "")
        String wavName,
        @WebParam(name = "language", targetNamespace = "")
        String language,
        @WebParam(name = "isOverwrite", targetNamespace = "")
        boolean isOverwrite);

    /**
     * 删除人声音频
     * 
     * @param wavName
     * @param language
     * @return
     *     returns com.pachira.tts.ws.client.MyResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteWav", targetNamespace = "http://service.ws.voice.pachira.com/", className = "com.pachira.tts.ws.client.DeleteWav")
    @ResponseWrapper(localName = "deleteWavResponse", targetNamespace = "http://service.ws.voice.pachira.com/", className = "com.pachira.tts.ws.client.DeleteWavResponse")
    public MyResp deleteWav(
        @WebParam(name = "wavName", targetNamespace = "")
        String wavName,
        @WebParam(name = "language", targetNamespace = "")
        String language);

    /**
     * 检查人声音频是否存在
     * 
     * @param wavName
     * @param language
     * @return
     *     returns com.pachira.tts.ws.client.MyResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkWavName", targetNamespace = "http://service.ws.voice.pachira.com/", className = "com.pachira.tts.ws.client.CheckWavName")
    @ResponseWrapper(localName = "checkWavNameResponse", targetNamespace = "http://service.ws.voice.pachira.com/", className = "com.pachira.tts.ws.client.CheckWavNameResponse")
    public MyResp checkWavName(
        @WebParam(name = "wavName", targetNamespace = "")
        String wavName,
        @WebParam(name = "language", targetNamespace = "")
        String language);

}
